# Generated by Django 2.2.7 on 2019-11-16 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20191116_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='search',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
